config/routes.rb
Rails.application.routes.draw do
  get 'admin/stats'
  get 'admin/info'
  post 'admin/new'
  devise_for :users
  get 'payments/new'
  get 'payments/paid'
  get 'payments/view'
  get 'payments/plan_each'
  post 'payments/plan_all'
  get 'payments/services_each'
  post 'payments/services_all'
  get 'payments/edit'
  get 'payments/show'
  get 'payments/download'
  resources :payments
  get 'contracts/main'
  get 'contracts/new'
  get 'contracts/view'
  get 'contracts/show'
  get 'contracts/edit'
  get 'contracts/all'
  resources :contracts
  get 'contragents/del'
  get 'contragents/main'
  get 'contragents/view'
  get 'contragents/edit'
  get 'contragents/dump'
  resources :contragents
  get 'orgs/del'
  get 'orgs/main'
  get 'orgs/view'
  get 'orgs/dump'
  get 'orgs/contracts'
  get 'orgs/edit'
  resources :orgs
  get 'main/index'
  root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/org.rb
class Org < ApplicationRecord
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController

  before_action :set_org, only: [ :show, :edit, :update, :del, :destroy]
  before_action :set_orgs, only: [ :main, :view]

  def main; end

  # Для отображения контрактов по организации
  def contracts
    @con = Contract.where(org_id: params[:id]).order(:end_date)
  end

  def new
    @org = Org.new
  end

  def view; end

  # Для отображения корзины
  def dump
    @orgs = Org.where(status: true)
  end

  # Для восстановления из корзины
  def del
    @org.update_attribute(:status, nil)
    redirect_to orgs_dump_path
  end

  # Для удаления организации из списка
  def destroy
    @org.update_attribute(:status, true)
    redirect_to orgs_view_path
  end

  def create
    @org = Org.new(org_params)
    @org.created_by = current_user.fio
    @org.last_cb = current_user.fio
    if @org.save
      redirect_to @org
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    @org.last_cb = current_user.fio
    if @org.update_attributes(org_params)
      redirect_to @org
    else
      render :edit
    end
  end

  private

  # Поиск организации
  def set_org
    @org = Org.find(params[:id])
  end

  # Показ неудаленных организаций
  def set_orgs
    @orgs = Org.where(status: nil)
  end

  # Получение параметров организации
  def org_params
    params.require(:org).permit(:name, :code, :person, :typ, :full_name, :small_name, :usedge, :account, :u_address, :f_address, :foreign, :square, :people, :space_fp)
  end
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/views/orgs/_org.html.erb
<%= form_for @org do |f|%>
  <div class="form-horizontal">
    <div class="form-group col-sm-8">
      <%= f.label :name, 'Название', class: 'col-sm-3 control-label'%>
      <div class="col-sm-9">
        <%= f.text_field :name, class: 'form-control',  placeholder: 'Название', required: true %>
      </div>
    </div>
    <div class="form-group col-sm-4">
      <%= f.label :code, 'Код', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :code, class: 'form-control',  placeholder: 'Код', required: true %>
      </div>
    </div>
    <h3 class="col-sm-offset-2">Основное</h3>
    <div class="form-group col-sm-6">
      <%= f.label :person, 'Юр./Физ. лицо', class: 'col-sm-4 control-label'%>
      <div class="col-sm-8">
        <%= f.select :person, [['Юр. лицо', 'Юр. лицо'], ['Физ. лицо', 'Физ. лицо']], {}, {class: 'form-control'}%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :typ, 'Тип организации', class: 'col-sm-2 control-label'%>
      <div class="col-sm-4">
        <%= f.select :typ, [['Бюджетная', 'Бюджетная'], ['Коммерческая', 'Коммерческая']], {}, {class: 'form-control'}%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :full_name, 'Полное название', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :full_name, class: 'form-control',  placeholder: 'Полное название', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :small_name, 'Сокращенное название', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :small_name, class: 'form-control',  placeholder: 'Сокращенное название', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :usedge, 'Использовать', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.select :usedge, [['Сокращенное название', 'Сокращенное название'], ['Полное название', 'Полное название']], {}, {class: 'form-control'}%>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <div class="checkbox">
          <%= f.check_box :foreign, {}, true, false %>
          <%= f.label :foreign, 'Отделение иностранной организации'%>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :account, 'Основной банковский счет', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :account, class: 'form-control',  placeholder: 'Счет', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :u_address, 'Юридический адрес', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :u_address, class: 'form-control',  placeholder: 'Юридический адрес', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :f_address, 'Фактический адрес', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :f_address, class: 'form-control',  placeholder: 'Фактический адрес', required: true %>
      </div>
    </div>
    <div class="form-group col-sm-4">
      <%= f.label :square, 'Площадь', class: 'col-sm-7 control-label'%>
      <div class="input-group col-sm-5">
        <%= f.text_field :square, class: 'form-control',  placeholder: 'Площадь', required: true %>
        <span class="input-group-addon">м<sup>2</sup></span>
      </div>
    </div>
    <div class="form-group col-sm-4">
      <%= f.label :people, 'Кол-во сотрудников', class: 'col-sm-6 control-label'%>
      <div class="col-sm-6">
        <%= f.text_field :people, class: 'form-control',  placeholder: 'Сотрудников', required: true %>
      </div>
    </div>
    <div class="form-group col-sm-5">
      <%= f.label :space_fp, 'Кол-во посадочных мест', class: 'col-sm-6 control-label'%>
      <div class="col-sm-6">
        <%= f.text_field :space_fp, class: 'form-control',  placeholder: 'Мест', required: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-ok"></span> Сохранить</button>
      </div>
    </div>
  </div>
<% end %>

app/views/orgs/contracts.html.erb
<div class="list-group col-md-2 person-md">
  <a href="main" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  Организации</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="dump" class="list-group-item"><span class="glyphicon glyphicon-trash"></span>  Удаленные</a>
</div>
<div class="col-md-10">
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Название</th>
      <th>Название организации</th>
      <th>Тип организации</th>
      <th>Дата окончания</th>
      <th>Статус</th>
      <th>Цена</th>
      <th>Оплата</th>
      <th>Подробнее</th>
      <th>Добавить оплату</th>
    </tr>
    </thead>
    <% @con.each do |f| %>
      <tr>
        <td><%= f.name %></td>
        <td><%= Org.where(id: f.org_id).first.small_name %></td>
        <td><%= Org.where(id: f.org_id).first.typ %></td>
        <td><%= f.end_date %></td>
        <td>
          <% if f.end_date < Time.now() %>
            Завершен
          <% else %>
            Активен
          <% end %>
        </td>
        <td><%= f.price %></td>
        <td>
          <% if Payment.where(contract_id: f.id, month: (Time.now() - Time.now().day.day + 1.day)).first.nil? %>
            <% s = 0 %>
          <% else %>
            <% s = Payment.where(contract_id: f.id, month: (Time.now() - Time.now().day.day + 1.day)).sum(:summ) %>
          <% end %>
          <% if s < f.price %>
            Не оплачено
          <% else %>
            Оплачено
          <% end %>
        </td>
        <td>
          <%= link_to f do %>
            <span class="glyphicon glyphicon-cog"></span>
          <% end %>
          <td>
            <%= link_to payments_new_path(id: f) do %>
              <span class="glyphicon glyphicon-ruble"></span>
            <% end %>
          </td>
          </td>
          </tr>
    <% end %>
  </table>
</div>

app/views/orgs/dump.html.erb
<div class="list-group col-md-2 person-md">
  <a href="main" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  Организации</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="dump" class="list-group-item"><span class="glyphicon glyphicon-trash"></span>  Удаленные</a>
</div>
<div class="col-md-10">
  <% if @orgs.length == 0 %>
    <h3>Корзина пуста</h3>
  <% else %>
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Наименнование</th>
        <th>Тип</th>
        <th>Сокращенное название</th>
        <th>Восстановить</th>
      </tr>
      </thead>
      <% @orgs.each do |f| %>
        <tr>
          <td><%= f.name %></td>
          <td><%= f.typ %></td>
          <td><%= f.small_name %></td>
          <td>
            <%= link_to orgs_del_path(id: f), data: { confirm: 'Вы уверены?'} do %>
              <span class="glyphicon glyphicon-ok"></span>
            <%end%>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/orgs/edit.html.erb
<div class="list-group col-md-2 person-md">
  <a href="main" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  Организации</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="dump" class="list-group-item"><span class="glyphicon glyphicon-trash"></span>  Удаленные</a>
</div>
<div class="col-md-10">
  <%= render 'org' %>
</div>

app/views/orgs/main.html.erb
<div class="list-group col-md-2 person-md">
  <a href="main" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  Организации</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="dump" class="list-group-item"><span class="glyphicon glyphicon-trash"></span>  Удаленные</a>
</div>
<div class="col-md-10">
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Наименнование</th>
        <th>Тип</th>
        <th>Сокращенное название</th>
        <% if current_user.admin == true %>
          <th>Создано</th>
          <th>Последнее обновление</th>
        <% end %>
        <th>Подробнее</th>
      </tr>
      </thead>
      <% @orgs.each do |f| %>
        <tr>
          <td><%= f.name %></td>
          <td><%= f.typ %></td>
          <td><%= f.small_name %></td>
          <% if current_user.admin == true %>
            <td><%= f.created_by + '; ' + f.created_at.to_s %></td>
            <td><%= f.last_cb + '; ' + f.updated_at.to_s %></td>
          <% end %>
          <td>
            <%= link_to f do %>
              <span class="glyphicon glyphicon-cog"></span>
            <%end%>
          </td>
        </tr>
      <% end %>
    </table>
</div>

app/views/orgs/new.html.erb
<div class="list-group col-md-2 person-md">
  <a href="main" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  Организации</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="dump" class="list-group-item"><span class="glyphicon glyphicon-trash"></span>  Удаленные</a>
</div>
<div class="col-md-10">
  <%= render 'org' %>
</div>

app/views/orgs/show.html.erb
<div class="list-group col-md-2 person-md">
  <a href="main" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  Организации</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="dump" class="list-group-item"><span class="glyphicon glyphicon-trash"></span>  Удаленные</a>
</div>
<div class="col-md-10">
  <div class="form-horizontal">
    <div class="form-group col-sm-8">
      <%= label :name, 'Название', class: 'col-sm-3 control-label'%>
      <div class="col-sm-9">
        <%= label :name, @org.name,  class: 'form-control'%>
      </div>
    </div>
    <div class="form-group col-sm-4">
      <%= label :code, 'Код', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :code, @org.code, class: 'form-control'%>
      </div>
    </div>
    <h3 class="col-sm-offset-2">Основное</h3>
    <div class="form-group">
      <%= label :person, 'Юр./Физ. лицо', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :person, @org.person, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :typ, 'Тип организации', class: 'col-sm-2 control-label'%>
      <div class="col-sm-4">
        <%= label :typ, @org.typ, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :full_name, 'Полное название', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :full_name, @org.full_name, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :small_name, 'Сокращенное название', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :small_name, @org.small_name, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :usedge, 'Использовать', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :usedge, @org.usedge, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :account, 'Основной банковский счет', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :account, @org.account, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :u_address, 'Юридический адрес', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :u_address, @org.u_address, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :f_address, 'Фактический адрес', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :f_address, @org.f_address, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group col-sm-4">
      <%= label :square, 'Площадь', class: 'col-sm-7 control-label'%>
      <div class="input-group col-sm-5">
        <%= label :square, "#{@org.square}м2", class: 'form-control'%>
      </div>
    </div>
    <div class="form-group col-sm-4">
      <%= label :people, 'Кол-во сотрудников', class: 'col-sm-6 control-label'%>
      <div class="col-sm-6">
        <%= label :people, @org.people, class: 'form-control'%>
        <%=  %>
      </div>
    </div>
    <div class="form-group col-sm-5">
      <%= label :space_fp, 'Кол-во посадочных мест', class: 'col-sm-6 control-label'%>
      <div class="col-sm-6">
        <%= label :space_fp, @org.space_fp, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= link_to orgs_edit_path(id: @org), class: "btn btn-default" do %>
          <span class="glyphicon glyphicon-cog"></span>
          Редактировать
        <% end %>
        <%= link_to @org, method: :delete, data: { confirm: 'Вы уверены?'}, class: "btn btn-default" do %>
          <span class="glyphicon glyphicon-trash"></span>
          Удалить
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orgs/view.html.erb
<div class="list-group col-md-2 person-md">
  <a href="main" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  Организации</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="dump" class="list-group-item"><span class="glyphicon glyphicon-trash"></span>  Удаленные</a>
</div>
<div class="col-md-10">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Название</th>
        <th>Полное название</th>
        <th>Подробнее</th>
        <th>Все контракты</th>
        <th>Удалить</th>
      </tr>
    </thead>
    <% @orgs.each do |f| %>
      <tr>
        <td><%= f.name %></td>
        <td><%= f.full_name %></td>
        <td>
          <%= link_to f do %>
            <span class="glyphicon glyphicon-cog"></span>
          <% end %>
        </td>
        <td>
        <%= link_to orgs_contracts_path(id: f) do %>
          <span class="glyphicon glyphicon-file"></span>
        <% end %>
        </td>
        <td>
          <%= link_to f, method: :delete, data: { confirm: 'Вы уверены?'} do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>