config/routes.rb
Rails.application.routes.draw do
  get 'admin/stats'
  get 'admin/info'
  post 'admin/new'
  devise_for :users
  get 'payments/new'
  get 'payments/paid'
  get 'payments/view'
  get 'payments/plan_each'
  post 'payments/plan_all'
  get 'payments/services_each'
  post 'payments/services_all'
  get 'payments/edit'
  get 'payments/show'
  get 'payments/download'
  resources :payments
  get 'contracts/main'
  get 'contracts/new'
  get 'contracts/view'
  get 'contracts/show'
  get 'contracts/edit'
  get 'contracts/all'
  resources :contracts
  get 'contragents/del'
  get 'contragents/main'
  get 'contragents/view'
  get 'contragents/edit'
  get 'contragents/dump'
  resources :contragents
  get 'orgs/del'
  get 'orgs/main'
  get 'orgs/view'
  get 'orgs/dump'
  get 'orgs/contracts'
  get 'orgs/edit'
  resources :orgs
  get 'main/index'
  root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contragent.rb
class Contragent < ApplicationRecord
end

app/controllers/contragents_controller.rb
class ContragentsController < ApplicationController

  before_action :set_cont, only: [ :show, :edit, :update, :del, :destroy]
  before_action :set_conts, only: [ :main, :view]

  def main; end

  def new
    @cont = Contragent.new
  end

  def view; end

  # Для отображения корзины
  def dump
    @conts = Contragent.where(status: true)
  end

  # Возврат из корзины
  def del
    @cont.update_attribute(:status, nil)
    redirect_to contragents_dump_path
  end

  # Добавление в корзину
  def destroy
    @cont.update_attribute(:status, true)
    redirect_to contragents_view_path
  end


  def create
    @cont = Contragent.new(cont_params)
    @cont.created_by = current_user.fio
    @cont.last_cb = current_user.fio
    if @cont.save
      redirect_to @cont
    else
      render :new
    end
  end

  def show;end

  def update
    @cont.last_cb = current_user.fio
    if @cont.update_attributes(cont_params)
      redirect_to @cont
    else
      render :edit
    end
  end

  def edit;end

  private

  # Поиск контрагента
  def set_cont
    @cont = Contragent.find(params[:id])
  end

  # Поиск неудаленных контрагентов
  def set_conts
    @conts = Contragent.where(status: nil)
  end

  # Получение параметров контрагента
  def cont_params
    params.require(:contragent).permit(:name, :code, :typ, :full_name, :group, :inn, :kpp, :code_okpo, :u_address, :f_address, :tel, :other, :bank_code, :code_name, :bank_name)
  end
end

app/helpers/contragents_helper.rb
module ContragentsHelper
end

app/views/contragents/_contr.html.erb
<%= form_for @cont do |f|%>
  <div class="form-horizontal">
    <div class="form-group col-sm-8">
      <%= f.label :name, 'Название', class: 'col-sm-3 control-label'%>
      <div class="col-sm-9">
        <%= f.text_field :name, class: 'form-control',  placeholder: 'Название', required: true %>
      </div>
    </div>
    <div class="form-group col-sm-4">
      <%= f.label :code, 'Код', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :code, class: 'form-control',  placeholder: 'Код', required: true %>
      </div>
    </div>
    <h3 class="col-sm-offset-2">Общие</h3>
    <div class="form-group">
      <%= f.label :typ, 'Юр./Физ. лицо', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.select :typ, [['Юр. лицо', 'Юр. лицо'], ['Физ. лицо', 'Физ. лицо']], {}, {class: 'form-control'}%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :group, 'Группа контрагентов', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :group, class: 'form-control',  placeholder: 'Группа контрагентов', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :full_name, 'Полное название', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :full_name, class: 'form-control',  placeholder: 'Полное название', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :inn, 'ИНН', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :inn, class: 'form-control',  placeholder: 'ИНН', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :kpp, 'КПП', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :kpp, class: 'form-control',  placeholder: 'КПП', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :code_okpo, 'Код по ОКПО', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :code_okpo, class: 'form-control',  placeholder: 'Код по ОКПО', required: true %>
      </div>
    </div>
    <h3 class="col-sm-offset-2">Адреса и телефоны</h3>
    <div class="form-group">
      <%= f.label :u_address, 'Юридический адрес', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :u_address, class: 'form-control',  placeholder: 'Юридический адрес', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :f_address, 'Фактический адрес', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :f_address, class: 'form-control',  placeholder: 'Фактический адрес', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :tel, 'Телефон', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.telephone_field :tel, class: 'form-control',  placeholder: 'Телефон', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :other, 'Другое', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :other, class: 'form-control',  placeholder: 'Любая другая контактная информация', required: true %>
      </div>
    </div>
    <h3 class="col-sm-offset-2">Банковский счет</h3>
    <div class="form-group">
      <%= f.label :bank_code, 'Код', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :bank_code, class: 'form-control',  placeholder: 'Код', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :code_name, 'Наименование', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :code_name, class: 'form-control',  placeholder: 'Наименование', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :bank_name, 'Банк', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :bank_name, class: 'form-control',  placeholder: 'Банк', required: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-ok"></span> Сохранить</button>
      </div>
    </div>
  </div>
<% end %>

app/views/contragents/dump.html.erb
<div class="list-group col-md-2 person-md">
  <a href="main" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  Контрагенты</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="dump" class="list-group-item"><span class="glyphicon glyphicon-trash"></span>  Удаленные</a>
</div>
<div class="col-md-10">
  <% if @conts.length == 0 %>
    <h3>Корзина пуста</h3>
  <% else %>
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Наименнование</th>
        <th>Тип</th>
        <th>Полное название</th>
        <th>Восстановить</th>
      </tr>
      </thead>
      <% @conts.each do |f| %>
        <tr>
          <td><%= f.name %></td>
          <td><%= f.typ %></td>
          <td><%= f.full_name %></td>
          <td>
            <%= link_to contragents_del_path(id: f), data: { confirm: 'Вы уверены?'} do %>
              <span class="glyphicon glyphicon-ok"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
  <% end %>
  </table>
</div>

app/views/contragents/edit.html.erb
<div class="list-group col-md-2 person-md">
  <a href="main" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  Организации</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="dump" class="list-group-item"><span class="glyphicon glyphicon-trash"></span>  Удаленные</a>
</div>
<div class="col-md-10">
  <%= render 'contr' %>
</div>

app/views/contragents/main.html.erb
<div class="list-group col-md-2 person-md">
  <a href="main" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  Контрагенты</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="dump" class="list-group-item"><span class="glyphicon glyphicon-trash"></span>  Удаленные</a>
</div>
<div class="col-md-10">
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Наименнование</th>
        <th>Тип</th>
        <th>Полное название</th>
        <% if current_user.admin == true %>
          <th>Создано</th>
          <th>Последнее обновление</th>
        <% end %>
        <th>Подробнее</th>
      </tr>
      </thead>
      <% @conts.each do |f| %>
        <tr>
          <td><%= f.name %></td>
          <td><%= f.typ %></td>
          <td><%= f.full_name %></td>
          <% if current_user.admin == true %>
            <td><%= f.created_by + '; ' + f.created_at.to_s %></td>
            <td><%= f.last_cb + '; ' + f.updated_at.to_s %></td>
          <% end %>
          <td>
            <%= link_to f do %>
              <span class="glyphicon glyphicon-cog"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
</div>

app/views/contragents/new.html.erb
<div class="list-group col-md-2 person-md">
  <a href="main" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  Контрагенты</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="dump" class="list-group-item"><span class="glyphicon glyphicon-trash"></span>  Удаленные</a>
</div>
<div class="col-md-10">
  <%= render 'contr' %>
</div>

app/views/contragents/show.html.erb
<div class="list-group col-md-2 person-md">
  <a href="main" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  Организации</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="dump" class="list-group-item"><span class="glyphicon glyphicon-trash"></span>  Удаленные</a>
</div>
<div class="col-md-10">
  <div class="form-horizontal">
    <div class="form-group col-sm-8">
      <%= label :name, 'Название', class: 'col-sm-3 control-label'%>
      <div class="col-sm-9">
        <%= label :name, @cont.name, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group col-sm-4">
      <%= label :code, 'Код', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :code, @cont.code, class: 'form-control'%>
      </div>
    </div>
    <h3 class="col-sm-offset-2">Общие</h3>
    <div class="form-group">
      <%= label :typ, 'Юр./Физ. лицо', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :typ, @cont.typ, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :group, 'Группа контрагентов', class: 'col-sm-2 control-label'%>
      <div class="col-sm-4">
        <%= label :group, @cont.group, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :full_name, 'Полное название', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :full_name, @cont.full_name, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :inn, 'ИНН', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :inn, @cont.inn, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :kpp, 'КПП', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :kpp, @cont.kpp, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :code_okpo, 'Код по ОКПО', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :code_okpo, @cont.code_okpo, class: 'form-control'%>
      </div>
    </div>
    <h3 class="col-sm-offset-2">Адреса и телефоны</h3>
    <div class="form-group">
      <%= label :u_address, 'Юридический адрес', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :u_address, @cont.u_address, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :f_address, 'Фактический адрес', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :f_address, @cont.f_address, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :tel, 'Телефон', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :tel, @cont.tel, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :other, 'Другое', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :other, @cont.other, class: 'form-control'%>
      </div>
    </div>
    <h3 class="col-sm-offset-2">Банковский счет</h3>
    <div class="form-group">
      <%= label :bank_code, 'Код', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :bank_code, @cont.bank_code, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :code_name, 'Наименование', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :code_name, @cont.code_name, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label :bank_name, 'Банк', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :bank_name, @cont.bank_name, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= link_to contragents_edit_path(id: @cont), class: "btn btn-default" do %>
          <span class="glyphicon glyphicon-cog"></span>
          Редактировать
        <% end %>
        <%= link_to @cont, method: :delete, data: { confirm: 'Вы уверены?'}, class: "btn btn-default" do %>
          <span class="glyphicon glyphicon-trash"></span>
          Удалить
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/contragents/view.html.erb
<div class="list-group col-md-2 person-md">
  <a href="main" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  Контрагенты</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="dump" class="list-group-item"><span class="glyphicon glyphicon-trash"></span>  Удаленные</a>
</div>
<div class="col-md-10">
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Название</th>
      <th>Полное название</th>
      <th>Подробнее</th>
      <th>Удалить</th>
    </tr>
    </thead>
    <% @conts.each do |f| %>
      <tr>
        <td><%= f.name %></td>
        <td><%= f.full_name %></td>
        <td>
          <%= link_to f do %>
            <span class="glyphicon glyphicon-cog"></span>
          <% end %>
        </td>
        <td>
          <%= link_to f, method: :delete, data: { confirm: 'Вы уверены?'} do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>