config/routes.rb
Rails.application.routes.draw do
  get 'admin/stats'
  get 'admin/info'
  post 'admin/new'
  devise_for :users
  get 'payments/new'
  get 'payments/paid'
  get 'payments/view'
  get 'payments/plan_each'
  post 'payments/plan_all'
  get 'payments/services_each'
  post 'payments/services_all'
  get 'payments/edit'
  get 'payments/show'
  get 'payments/download'
  resources :payments
  get 'contracts/main'
  get 'contracts/new'
  get 'contracts/view'
  get 'contracts/show'
  get 'contracts/edit'
  get 'contracts/all'
  resources :contracts
  get 'contragents/del'
  get 'contragents/main'
  get 'contragents/view'
  get 'contragents/edit'
  get 'contragents/dump'
  resources :contragents
  get 'orgs/del'
  get 'orgs/main'
  get 'orgs/view'
  get 'orgs/dump'
  get 'orgs/contracts'
  get 'orgs/edit'
  resources :orgs
  get 'main/index'
  root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/controllers/payments_controller.rb
require_relative 'payment_report'

class PaymentsController < ApplicationController

  before_action :set_pay, only: [ :show, :edit, :update, :paid]

  def new
    @con = Contract.find(params[:id]) if !params[:id].nil?
    @pay = Payment.new
  end

  def services_each; end

  # Для отображения статистики по услугам за указанный месяц
  def services_all
    @f = 0
    @p = 0
    @date = Date.civil(params[:month]["month(1i)"].to_i,
                       params[:month]["month(2i)"].to_i,
                       params[:month]["month(3i)"].to_i)
    @con = Contract.where(end_date: @date.to_s..'2100-09-13', podp_date: '2000-09-13'..(@date + 1.month).to_s)
    @pays = Payment.where(month: @date)
    @con.each { |n| @p += n.price }
    @pays.each { |n| @f += n.summ }
  end

  # Для отображения статистики по контрактам за указанный месяц
  def plan_all
    @f = 0
    @p = 0
    @date = Date.civil(params[:month]["month(1i)"].to_i,
                       params[:month]["month(2i)"].to_i,
                       params[:month]["month(3i)"].to_i)
    @con = Contract.where(end_date: @date.to_s..'2100-09-13', podp_date: '2000-09-13'..(@date + 1.month).to_s)
    @pays = Payment.where(month: @date)
    @con.each { |n| @p += n.price + n.price_nds }
    @pays.each { |n| @f += n.summ }
  end

  def plan_each; end

  # Для формирования печатной версии счета
  def download
    name = params[:number]
    # Удаление сущестующей печатной версии отчета с таким же именем, если он существует
    File.delete("#{Rails.root}/public/#{name}.docx") if File.file?("#{Rails.root}/public/#{name}.docx")
    pay = Payment.where(file_name: name).first
    con = Contract.where(id: pay.contract_id).first
    mas = []
    # Проверка по каждой услуге и занесение в массив

    if con.gvs == 'true'
      mass = []
      mass << 'gvs'
      mass << con.v_gvs
      mass << con.t_gvs
      mass << con.o_gvs
      mas << mass
    end
    if con.hvs == 'true'
      mass = []
      mass << 'hvs'
      mass << con.v_hvs
      mass << con.t_hvs
      mass << con.o_hvs
      mas << mass
    end
    if con.vgvs == 'true'
      mass = []
      mass << 'vgvs'
      mass << con.v_vgvs
      mass << con.t_vgvs
      mass << con.o_vgvs
      mas << mass
    end
    if con.vhvs == 'true'
      mass = []
      mass << 'vhvs'
      mass << con.v_vhvs
      mass << con.t_vhvs
      mass << con.o_vhvs
      mas << mass
    end
    if con.otop == 'true'
      mass = []
      mass << 'otop'
      mass << con.v_otop
      mass << con.t_otop
      mass << con.o_otop
      mas << mass
    end
    if con.exp == 'true'
      mass = []
      mass << 'exp'
      mass << con.v_exp
      mass << con.t_exp
      mass << con.o_exp
      mas << mass
    end
    if con.tbo == 'true'
      mass = []
      mass << 'tbo'
      mass << con.v_tbo
      mass << con.t_tbo
      mass << con.o_tbo
      mas << mass
    end
    # Сборка файла
    PaymentReport.new.make_file(name, pay, mas)
    # Отправка файла
    send_file("#{Rails.root}/public/#{name}.docx")
  end

  # Простановка счета оплаченным
  def paid
    @pay.paid = true
    @pay.summ = Contract.find(@pay.contract_id).price + Contract.find(@pay.contract_id).price_nds + @pay.perep
    @pay.save
    redirect_to payments_view_path
  end

  def create
    @pay = Payment.new(pay_params)
    @pay.created_by = current_user.fio
    @pay.last_cb = current_user.fio
    @pay.file_name = @pay.number
    @pay.summ = 0
    if @pay.save
      redirect_to @pay
    else
      render :new
    end
  end

  def show; end

  def view
    @pays = Payment.all
  end

  def edit; end

  def update
    @pay.last_cb = current_user.fio
    @pay.file_name = @pay.number
    if @pay.update_attributes(pay_paramss)
      @pay.summ = 0 if @pay.paid != true
      @pay.summ = Contract.find(@pay.contract_id).price + Contract.find(@pay.contract_id).price_nds + @pay.perep if @pay.paid == true
      @pay.save
      redirect_to @pay
    else
      render :edit
    end
  end

  private

  def set_pay
    @pay = Payment.find(params[:id])
  end

  def pay_paramss
    params.require(:payment).permit(:number, :date, :month, :nazn, :perep)
  end

  def pay_params
    params.require(:payment).permit(:number, :date, :month, :contract_id, :nazn, :perep)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_pay.html.erb
<%= form_for @pay do |f|%>
  <div class="form-horizontal">
    <div class="form-group col-sm-8">
      <%= f.label :number, 'Номер', class: 'col-sm-3 control-label'%>
      <div class="col-sm-9">
        <%= f.text_field :number, class: 'form-control',  placeholder: 'Номер', required: true %>
      </div>
    </div>
    <div class="form-group col-sm-4">
      <%= f.label :date, 'От', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.date_select :date, class: 'form-control',  placeholder: 'От', required: true %>
      </div>
    </div>
    <div class="form-group">
    </div>
    <% if !current_page?(payments_edit_path) %>
      <h3 class="col-sm-offset-2">Контракт</h3>
      <div class="form-group">
        <%= f.label :contract_id, 'Контракт', class: 'col-sm-2 control-label'%>
        <div class="col-sm-10">
          <% if @con.nil? %>
            <%= f.select :contract_id, Contract.where(end_date: Time.now()..'2100-09-13').collect{ |p| [ p.name + '; Плановая сумма оплаты: ' + p.price.to_s, p.id]}, {}, {class: 'form-control'}%>
          <% else %>
            <%= f.select :contract_id,[[@con.name + '; Плановая сумма оплаты: ' + @con.price.to_s, @con.id]], {}, {class: 'form-control', value: @con.id}%>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :month, 'За', class: 'col-sm-2 control-label'%>
      <div class="col-sm-4">
        <%= f.date_select :month, {:discard_day => true} , class: 'form-control',  placeholder: 'От', required: true%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :nazn, 'Назначение платежа', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :nazn, class: 'form-control',  placeholder: 'Коммунальные и эксплуатационные услуги', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :perep, 'Переплата', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :perep, class: 'form-control',  placeholder: 'Проставляется после получения оплаты, если имеется переплата', required: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-ok"></span> Сохранить</button>
      </div>
    </div>
  </div>
<% end %>

app/views/payments/edit.html.erb
<div class="list-group col-md-2 person-md">
  <a href="plan_each" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  План / Факт</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="services_each" class="list-group-item"><span class="glyphicon glyphicon-folder-open"></span>  Расход по услугам</a>
</div>
<div class="col-md-10">
  <%= render 'pay' %>
</div>

app/views/payments/new.html.erb
<div class="list-group col-md-2 person-md">
  <a href="plan_each" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  План / Факт</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="services_each" class="list-group-item"><span class="glyphicon glyphicon-folder-open"></span>  Расход по услугам</a>
</div>
<div class="col-md-10">
  <%= render 'pay' %>
</div>

app/views/payments/plan_all.html.erb
<div class="list-group col-md-2 person-md">
  <a href="plan_each" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  План / Факт</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="services_each" class="list-group-item"><span class="glyphicon glyphicon-folder-open"></span>  Расход по услугам</a>
</div>
<div class="col-md-10">
  <h3>Анализ по всем контрактам</h3>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Всего контрактов</th>
      <th>Сумма по плану (руб.)</th>
      <th>Сумма по факту (руб.)</th>
    </tr>
    </thead>
      <tr>
        <td><%= @con.length %></td>
        <td><%= @p %></td>
        <td><%= @f %></td>
      </tr>
  </table>
  <h3>Анализ по каждому контракту</h3>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Контракт</th>
      <th>Сумма по контракту (руб.)</th>
      <th>Сумма по факту (руб.)</th>
      <th>Число платежей</th>
      <th>Подробнее о контракте</th>
    </tr>
    </thead>
    <% @con.each do |f| %>
      <tr>
        <% s = f.price.to_s + ' + ' + f.price_nds.to_s + '(НДС) = ' + (f.price + f. price_nds).to_f.to_s %>
        <td><%= f.name %></td>
        <td><%= s %></td>
        <td>
          <% if Payment.where(contract_id: f.id, month: @date).first.nil? %>
            0
          <% else %>
            <%= Payment.where(contract_id: f.id, month: @date).sum(:summ) %>
          <% end %>
        </td>
        <td><%= Payment.where(contract_id: f.id, month: @date).count %></td>
        <td>
          <%= link_to f do %>
            <span class="glyphicon glyphicon-cog"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/payments/plan_each.html.erb
<div class="list-group col-md-2 person-md">
  <a href="plan_each" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  План / Факт</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="services_each" class="list-group-item"><span class="glyphicon glyphicon-folder-open"></span>  Расход по услугам</a>
</div>
<div class="col-md-10">
  <%= form_tag payments_plan_all_path do%>
    <h3>Выберите месяц и год для анализа</h3>
    <div class="form-group">
      <div class="col-sm-4">
        <%= date_select :month, :month, {:discard_day => true} , class: 'form-control',  placeholder: 'От', required: true%>
      </div><br>
    </div>
    <div class="form-group">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Поиск</button>
      </div>
    </div>
  <% end %>
</div>

app/views/payments/services_all.html.erb
<div class="list-group col-md-2 person-md">
  <a href="plan_each" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  План / Факт</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="services_each" class="list-group-item"><span class="glyphicon glyphicon-folder-open"></span>  Расход по услугам</a>
</div>
<div class="col-md-10">
  <h3>Анализ по всем контрактам (в () сумма с НДС)</h3>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Сумма по плану всего (руб.)</th>
        <th>Сумма по факту всего (руб.)</th>
        <th>ГВС</th>
        <th>ХВС</th>
        <th>Вод. ГВС</th>
        <th>Вод. ХВС</th>
        <th>Отопление</th>
        <th>Эксп Усл</th>
        <th>ТБО</th>
      </tr>
    </thead>
    <tr>
      <td><%= @con.sum(:price).to_s + ' + ' + @con.sum(:price_nds).to_s + '(НДС) = ' + (@con.sum(:price) + @con.sum(:price_nds)).to_s %></td>
      <td><%= @pays.sum(:summ) %></td>
      <td>
        <%= @con.sum(:o_gvs) %>
        <%= '(' + (@con.sum(:o_gvs) * 1.18).round(2).to_s + ')' %>
      </td>
      <td>
        <%= @con.sum(:o_hvs) %>
        <%= '(' + (@con.sum(:o_hvs) * 1.18).round(2).to_s + ')' %>
      </td>
      <td>
        <%= @con.sum(:o_vgvs) %>
        <%= '(' + (@con.sum(:o_vgvs) * 1.18).round(2).to_s + ')' %>
      </td>
      <td>
        <%= @con.sum(:o_vhvs) %>
        <%= '(' + (@con.sum(:o_vhvs) * 1.18).round(2).to_s + ')' %>
      </td>
      <td>
        <%= @con.sum(:o_otop) %>
        <%= '(' + (@con.sum(:o_otop) * 1.18).round(2).to_s + ')' %>
      </td>
      <td>
        <%= @con.sum(:o_exp) %>
        <%= '(' + (@con.sum(:o_exp) * 1.18).round(2).to_s + ')' %>
      </td>
      <td>
        <%= @con.sum(:o_tbo) %>
        <%= '(' + (@con.sum(:o_tbo) * 1.18).round(2).to_s + ')' %>
      </td>
    </tr>
  </table>
  <h3>Анализ по каждому контракту (в () сумма с НДС)</h3>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Контракт</th>
      <th>Сумма по контракту (руб.)</th>
      <th>Сумма по факту (руб.)</th>
      <th>ГВС</th>
      <th>ХВС</th>
      <th>Вод. ГВС</th>
      <th>Вод. ХВС</th>
      <th>Отопление</th>
      <th>Эксп Усл</th>
      <th>ТБО</th>
      <th>Подробнее о контракте</th>
    </tr>
    </thead>
    <% @con.each do |f| %>
      <tr>
        <td><%= f.name %></td>
        <td><%= f.price.to_s + ' + ' + f.price_nds.to_s + '(НДС) = ' + (f.price + f.price_nds).to_s %></td>
        <td>
          <% if Payment.where(contract_id: f.id, month: @date).first.nil? %>
            0
          <% else %>
            <%= Payment.where(contract_id: f.id, month: @date).sum(:summ) %>
          <% end %>
        </td>
        <td>
          <%= f.o_gvs %>
          <%= '(' + (f.o_gvs.to_f * (f.nds.to_f * 0.01 + 1)).to_f.round(2).to_s + ')' if !f.o_gvs.nil?%>
        </td>
        <td>
          <%= f.o_hvs %>
          <%= '(' + (f.o_hvs.to_f * (f.nds.to_f * 0.01 + 1)).to_f.round(2).to_s + ')' if !f.o_hvs.nil?%>
        </td>
        <td>
          <%= f.o_vgvs %>
          <%= '(' + (f.o_vgvs.to_f * (f.nds.to_f * 0.01 + 1)).to_f.round(2).to_s + ')' if !f.o_vgvs.nil?%>
        </td>
        <td>
          <%= f.o_vhvs %>
          <%= '(' + (f.o_vhvs.to_f * (f.nds.to_f * 0.01 + 1)).to_f.round(2).to_s + ')' if !f.o_vhvs.nil?%>
        </td>
        <td>
          <%= f.o_otop %>
          <%= '(' + (f.o_otop.to_f * (f.nds.to_f * 0.01 + 1)).to_f.round(2).to_s + ')' if !f.o_otop.nil?%>
        </td>
        <td>
          <%= f.o_exp %>
          <%= '(' + (f.o_exp.to_f * (f.nds.to_f * 0.01 + 1)).to_f.round(2).to_s + ')' if !f.o_exp.nil?%>
        </td>
        <td>
          <%= f.o_tbo %>
          <%= '(' + (f.o_tbo.to_f * (f.nds.to_f * 0.01 + 1)).to_f.round(2).to_s + ')' if !f.o_tbo.nil?%>
        </td>
        <td>
          <%= link_to f do %>
            <span class="glyphicon glyphicon-cog"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/payments/services_each.html.erb
<div class="list-group col-md-2 person-md">
  <a href="plan_each" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  План / Факт</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="services_each" class="list-group-item"><span class="glyphicon glyphicon-folder-open"></span>  Расход по услугам</a>
</div>
<div class="col-md-10">
  <%= form_tag payments_services_all_path do%>
    <h3>Выберите месяц и год для анализа</h3>
    <div class="form-group">
      <div class="col-sm-4">
        <%= date_select :month, :month, {:discard_day => true} , class: 'form-control',  placeholder: 'От', required: true%>
      </div><br>
    </div>
    <div class="form-group">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Поиск</button>
      </div>
    </div>
  <% end %>
</div>

app/views/payments/show.html.erb
<div class="list-group col-md-2 person-md">
  <a href="plan_each" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  План / Факт</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="services_each" class="list-group-item"><span class="glyphicon glyphicon-folder-open"></span>  Расход по услугам</a>
</div>
<div class="col-md-10">
  <div class="form-horizontal">
    <div class="form-group col-sm-8">
      <%= label :number, 'Номер', class: 'col-sm-3 control-label'%>
      <div class="col-sm-9">
        <%= label :number, @pay.number, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group col-sm-4">
      <%= label :date, 'От', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :date, @pay.date, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
    </div>
    <h3 class="col-sm-offset-2">Контракт</h3>
    <div class="form-group">
      <%= label :contract_id, 'Контракт', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :contract_id, Contract.where(id: @pay.contract_id).first.name, {}, {class: 'form-control'} %>
      </div>
    </div>
    <div class="form-group">
      <%= label :month, 'За', class: 'col-sm-2 control-label'%>
      <div class="col-sm-4">
        <%= label :month, @pay.month, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= label :nazn, 'Назначение платежа', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :nazn, @pay.nazn, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= label :perep, 'Переплата', class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= label :perep, @pay.perep, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= link_to payments_edit_path(id: @pay), class: "btn btn-default" do %>
          <span class="glyphicon glyphicon-cog"></span>
          Редактировать
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/payments/view.html.erb
<div class="list-group col-md-2 person-md">
  <a href="plan_each" class="list-group-item"><span class="glyphicon glyphicon-home"></span>  План / Факт</a>
  <a href="new" class="list-group-item"><span class="glyphicon glyphicon-plus"></span>  Добавить</a>
  <a href="view" class="list-group-item"><span class="glyphicon glyphicon-pencil"></span>  Просмотр и редактирование</a>
  <a href="services_each" class="list-group-item"><span class="glyphicon glyphicon-folder-open"></span>  Расход по услугам</a>
</div>
<div class="col-md-10">
  <table class="table table-hover">
  <thead>
  <tr>
    <th>Номер</th>
    <th>Контракт</th>
    <th>За</th>
    <th>Сумма</th>
    <% if current_user.admin == true %>
      <th>Создано</th>
      <th>Последнее обновление</th>
    <% end %>
    <th>Оплачено</th>
    <th>Подробнее</th>
    <th>Загрузить</th>
  </tr>
  </thead>
  <% @pays.each do |f| %>
    <tr>
      <td><%= f.number %></td>
      <td><%= Contract.where(id: f.contract_id).first.name %></td>
      <td><%=' Месяц: ' + f.month.month.to_s + '; Год: ' + f.month.year.to_s %></td>
      <td><%= Contract.find(f.contract_id).price.to_s + ' + ' + Contract.find(f.contract_id).price_nds.to_s + '(НДС) = ' + (Contract.find(f.contract_id).price + Contract.find(f.contract_id).price_nds).to_s  %></td>
      <% if current_user.admin == true %>
        <td><%= f.created_by + '; ' + f.created_at.to_s %></td>
        <td><%= f.last_cb + '; ' + f.updated_at.to_s %></td>
      <% end %>
      <td>
        <% if !f.paid? %>
        <%= link_to payments_paid_path(id: f.id) do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %>
        <% else %>
          <span class="glyphicon glyphicon-ok"></span>
        <% end %>
      </td>
      <td>
        <%= link_to f do %>
          <span class="glyphicon glyphicon-cog"></span>
        <% end %>
      </td>
      <td>
        <%= link_to payments_download_path(number: f.file_name) do %>
          <span class="glyphicon glyphicon-download-alt"></span>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
</div>