config/routes.rb
Rails.application.routes.draw do
  get 'admin/stats'
  get 'admin/info'
  post 'admin/new'
  devise_for :users
  get 'payments/new'
  get 'payments/paid'
  get 'payments/view'
  get 'payments/plan_each'
  post 'payments/plan_all'
  get 'payments/services_each'
  post 'payments/services_all'
  get 'payments/edit'
  get 'payments/show'
  get 'payments/download'
  resources :payments
  get 'contracts/main'
  get 'contracts/new'
  get 'contracts/view'
  get 'contracts/show'
  get 'contracts/edit'
  get 'contracts/all'
  resources :contracts
  get 'contragents/del'
  get 'contragents/main'
  get 'contragents/view'
  get 'contragents/edit'
  get 'contragents/dump'
  resources :contragents
  get 'orgs/del'
  get 'orgs/main'
  get 'orgs/view'
  get 'orgs/dump'
  get 'orgs/contracts'
  get 'orgs/edit'
  resources :orgs
  get 'main/index'
  root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Жилищник</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <% if controller_name == 'main' || current_page?(root_path) %>
              <li class="active"><a href="/main/index">Главная<span class="sr-only">(current)</span></a></li>
            <% else %>
              <li><a href="/main/index">Главная<span class="sr-only">(current)</span></a></li>
            <% end %>
            <% if controller_name == 'orgs' %>
              <li class="active"><a href="/orgs/main">Организации<span class="sr-only">(current)</span></a></li>
            <% else %>
              <li><a href="/orgs/main">Организации</a></li>
            <% end %>
            <% if controller_name == 'contragents' %>
              <li class="active"><a href="/contragents/main">Контрагенты</a></li>
            <% else %>
              <li><a href="/contragents/main">Контрагенты</a></li>
            <% end %>
            <% if controller_name == 'contracts' %>
              <li class="active"><a href="/contracts/main">Контракты</a></li>
            <% else %>
              <li><a href="/contracts/main">Контракты</a></li>
            <% end %>
            <% if controller_name == 'payments' %>
              <li class="active"><a href="/payments/view">Счет</a></li>
            <% else %>
              <li><a href="/payments/view">Счет</a></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user.admin == true %>
              <% if current_page?(admin_info_path) %>
                <li class="active"><%= link_to 'Информация об организации', admin_info_path %></li>
              <% else %>
                <li><%= link_to 'Информация об организации', admin_info_path %></li>
              <% end %>
            <% end %>
            <% if current_user.admin == true %>
              <% if current_page?(admin_stats_path) %>
                <li class="active"><%= link_to 'Административная панель', admin_stats_path %></li>
              <% else %>
                <li><%= link_to 'Админимстративная панель', admin_stats_path %></li>
              <% end %>
            <% end %>
            <% if current_page?(edit_user_registration_path) %>
              <li class="active"><%= link_to 'Личный кабинет', edit_user_registration_path %></li>
            <% else %>
              <li><%= link_to 'Личный кабинет', edit_user_registration_path %></li>
            <% end %>
            <li><%= link_to 'Выход', destroy_user_session_path, method: :delete %></li>
          </ul>
          <% else %>
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to "Вход", new_user_session_path %></li>
            </ul>
          <% end %>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="col-md-10">
      <%= yield %>
    </div>
    <% if user_signed_in? %>
      <div class="list-group col-md-2 person-md">
        <div class="list-group person-md">
          <% flash.each do |key, message| %>
            <div class="alert alert-<%= key %>"><%= message %></div>
          <% end %>
        </div>
        <div class="list-group person-md">
          <% if @conn.length == 0 %>
            <p class="list-group-item">Завершающихся контрактов нет</p>
          <% else %>
            <p class="list-group-item">Завершающиеся контракты:</p>
            <% @conn.each do |f| %>
              <%= link_to contracts_main_path, class: "list-group-item" do %>
                <span class="badge"><%= f.end_date %></span>
                <%= f.name %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </body>
</html>